### ISSUE TITLE
JSON : Armures

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/libupsystem#60]
modification des valeurs des rangs d'armure en points

modification des valeurs des effets des armures (réduction des dégâts et et bonus au ND)

modification des valeurs en points des pièces d'armure (y compris boucliers)

suppression des matériaux de boucliers (répercussions sur le code)

suppression des malus d'esquive et de parade des diverses pièces d'armure

ajout du tableau "malus_armure": [0, 1, 2, 3, 4, 5] 
=> répercussions sur le code

**Comment by audreyazura** [comment]
Rang, réductions de dégât, bonus au ND et valeur en points changés. Je fais passer les tests et je lance la pull request.

**Comment by audreyazura** [comment]
Intégration des malus d'armure, suppression des malus par pièce et suppression des matériaux de boucliers effectuées.
