### ISSUE TITLE
JSON Armes

### ISSUE THREAD

**Issue by ykonoclast** [ykonoclast/libupsystem#61]
**suppression des armes :** adaga(lame), darn dao, kastane, manople, shi zi jian, shuan gao, tulwar, dao, dilmekiri, épée bâtarde (version une et deux mains), kan dao, tieh shan gong, canif, niur er jan dao, panzerfaust, paku, shuang huang, fourche, hu tsa, vouge, shua tou quiang, shuan pian yue, shuan pian yue ya chan, jiu jie bien, sa tjat koen, arbalète de poing, chu ko nu, mei far chen, sarbacane, arquebuse, mousqueton, 

**renommage :** épée longue devient épée à une main, bâton devient bâton ferré,

**ajout :** il semblerait que le mousquet ne soit pas présent (il y a le "fusil" je pense que c'est le moderne).

**Modifier toutes les VD**

**vérifier les "notes"** (physique minimal, malus à l'attaque...)

**Comment by audreyazura** [comment]
Beaucoup des armes à supprimer n'était déjà pas présente dans le fichier. Celle qui y était ont été enlevée.

Renommage effectué.

Mousquet était présent et a été vérifié.

Les notes ont été vérifiées et mises à jour.

Je fais les armures et ferais ensuite une passe sur les tests avant de briser le code en changeant les dégâts.

**Comment by ykonoclast** [comment]
C'est étonnant qu'elles n'y soient pas car j'ai fait la liste avec le fichier justement. Tu es sur?

**Comment by audreyazura** [comment]
J'ai pourtant bien fait un pull avant de commencer... Et avec des ctrl+f, la plupart n'était pas trouvable. Je me rappelle bien les avoir supprimer lors du passage au UP V.4.5. Peut-être que je n'avais pas fait de pull-request à l'époque ?

**Comment by ykonoclast** [comment]
Certainement, aucune activité sur le github n'est enreigstrée après septembre à part le changement de nom de mon compte en novembre et ta dernière pull request date de juin ou juillet.

Bon j'aurai tout d'un seul coup!

**Comment by audreyazura** [comment]
Remplacement des dés de dégâts par les VD effectués. Attention, ça va crier.
